---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(googlesheets4)
library(kableExtra)
library(tidyverse)
```

## Prioriteringsliste

```{r}
dat <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1dlU5Wtv3d0fqDN_4jTuNkMTLEcckNYuHB_gSp8zCKwM/edit#gid=1976769141",
                                 sheet = "prioriteringsliste")
```

```{r}
kbl(dat, align="ll") %>%
   kable_classic("striped",
                 full_width = F) %>%
  row_spec(0, bold=T) %>%
  save_kable("prioriteringsliste.jpg", 
             zoom = 2)
```

## Måltekst og antall indikatorer per mål

```{r}
mal <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1dlU5Wtv3d0fqDN_4jTuNkMTLEcckNYuHB_gSp8zCKwM/edit#gid=1976769141",
                                 sheet = "Måltekst")

```

```{r}
mal %>%
  select(c("Mål", "Stikkord", "Måltekst")) %>%
  kbl(align="ll") %>%
  kable_classic("striped",
                 full_width = F) %>%
  row_spec(0, bold=T) %>%
  save_kable("maltekst.jpg", 
             zoom = 2)
```

```{r}
options(knitr.kable.NA = '')
mal %>%
  select(c("Mål", "Stikkord", "Headline", "Component", "Complementary",
           "Miljøindikatorer", "Nasjonale målepunkt")) %>%
  mutate("Mål" = as.character(Mål)) %>%
  add_row("Mål" = "",
          Stikkord = "Sum",
          Headline = sum(mal$Headline),
          Component = sum(mal$Component),
          Complementary = sum(mal$Complementary),
          "Miljøindikatorer" = NA,
          "Nasjonale målepunkt" = NA) %>%
  kbl(align="ll") %>%
  kable_classic("striped",
                 full_width = F) %>%
 column_spec(3, color = "white",
             background = spec_color(mal$Headline, end = 0.7)) %>%
 column_spec(4, color = "white",
             background = spec_color(mal$Component, end = 0.7)) %>%
 column_spec(5, color = "white",
             background = spec_color(mal$Complementary, end = 0.7)) %>%
 column_spec(6, color = "white",
             background = spec_color(mal$Miljøindikatorer, end = 0.7)) %>%
 column_spec(7, color = "white",
             background = spec_color(mal$`Nasjonale målepunkt`, end = 0.7)) %>%
  row_spec(15, background = "white", color = "black") %>%
  row_spec(0, bold=T) %>%
  save_kable("indikatorerPerMal.jpg", 
             zoom = 2)
```



Samme tabell som over, men bare med 'tilgjengelige' indikatorer

```{r}
mal %>%
  select(c("Mål", "Stikkord", Headline = Headline2, Component = Component2)) %>%
  mutate("Mål" = as.character(Mål)) %>%
  add_row("Mål" = "",
          Stikkord = "Sum",
          Headline = sum(mal$Headline2),
          Component = sum(mal$Component2)) %>%
  kbl(align="ll") %>%
  kable_classic("striped",
                 full_width = F) %>%
 column_spec(3, color = "white",
             background = spec_color(mal$Headline2, end = 0.7)) %>%
 column_spec(4, color = "white",
             background = spec_color(mal$Component2, end = 0.7)) %>%
  row_spec(0, bold=T) %>%
  row_spec(15, background = "white", color = "black") %>%
  save_kable("tables/tilgjengeligeIndikatorerPerMal.jpg", 
             zoom = 2)
```
## Indikatorer

```{r}
ind <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1dlU5Wtv3d0fqDN_4jTuNkMTLEcckNYuHB_gSp8zCKwM/edit#gid=1976769141",
                                 sheet = "Indikatorer",
                                 range = "A:D",
                                 col_types = "c")
# eget ark med bærekraftsindikatorerne til FN kombinert med najosnale målepunkt
barekraft <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1dlU5Wtv3d0fqDN_4jTuNkMTLEcckNYuHB_gSp8zCKwM/edit#gid=1976769141",
                                 sheet = "bærekraft",
                                 range = "A:B",
                                 col_types = "c")
```
Klargjør bærekraftsindikatorene ved å slå sammen duplikater
```{r}
comb <- barekraft %>%
  pivot_wider(names_from = target,
              values_from = target)%>%
  unite(target,  -Indikatorer, sep=",", na.rm=T) %>%
  add_column(Type = "Bærekraftsindikator") %>%
  bind_rows(ind)
```


Tell antall rader for hver gruppe

```{r}

hl <- nrow(comb[comb$Type=="Hovedindikator",])
co <- nrow(comb[comb$Type=="Komponent",])
cm <- nrow(comb[comb$Type=="Komplementær",])
mi <- nrow(comb[comb$Type=="Miljøindikator",])
bk <- nrow(comb[comb$Type=="Bærekraftsindikator",])

a <- hl
b <- hl+co
c <- b+cm
d <- c+mi
e <- d+bk
```

```{r}
comb %>%
  mutate(sortby = case_when(
    Type == "Hovedindikator" ~ 1,
    Type == "Komponent" ~2,
    Type == "Komplementær" ~ 3,
    Type == "Miljøindikator" ~ 4,
    Type == "Bærekraftsindikator" ~ 5
  )) %>%
  # extract first number from concatinated list
  mutate(sortby2 = as.numeric(str_split_i(target, ",", 1)))%>%
  arrange(sortby, sortby2) %>%
  filter(Type != "Egne forslag") %>%
  select(c("GBF mål" = target, "Indikatorer", "Status")) %>%
  kbl(align="ll",
      booktabs = TRUE) %>%
  kable_classic("striped",
                 full_width = F) %>%
  row_spec(0, bold=T) %>%
    pack_rows("Hovedindikatorer", 1, a, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Komponentindikatorer", a+1, b, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Komplementære indikatorer", b+1,c, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Miljøindikatorer", c+1,d, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Bærekraftsindikatorer", d+1,e, label_row_css = "background-color: #cef598; color: #000000;" ) #%>%
 
#The table is too long for an image. Copy the text in the output and paste directly (with formatting) into word 
#save_kable("indikatorer.jpg", 
 #            zoom = 2)
```

Same table, but sorted by status
```{r}
comb %>%
  mutate(sortby = case_when(
    Type == "Hovedindikator" ~ 1,
    Type == "Komponent" ~2,
    Type == "Komplementær" ~ 3,
    Type == "Miljøindikator" ~ 4,
    Type == "Bærekraftsindikator" ~ 5
  )) %>%
  # extract first number from concatinated list
  mutate(sortby2 = as.numeric(str_split_i(target, ",", 1)),
         sortby3 = case_when(
    Status == "Tilgjengelig" ~ 1,
    Status == "Under utvikling" ~ 2,
    Status == "Mangler data" ~ 3))%>%
  arrange(sortby, sortby3, sortby2) %>%
  filter(Type != "Egne forslag") %>%
  select(c("GBF mål" = target, "Indikatorer", "Status")) %>%
  kbl(align="ll",
      booktabs = TRUE) %>%
  kable_classic("striped",
                 full_width = F) %>%
  row_spec(0, bold=T) %>%
    pack_rows("Hovedindikatorer", 1, a, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Komponentindikatorer", a+1, b, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Komplementære indikatorer", b+1,c, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Miljøindikatorer", c+1,d, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Bærekraftsindikatorer", d+1,e, label_row_css = "background-color: #cef598; color: #000000;" )

ind %>%
  mutate(sortby = case_when(
    Type == "Headline" ~ 1,
    Type == "Component" ~2,
    Type == "Complementary" ~ 3,
    Type == "Miljøindikatorer" ~ 4,
    Type == "Bærekraftsindikatorer" ~ 5
  ),
  sortby2 = case_when(
    Status == "Tilgjengelig" ~ 1,
    Status == "Under utvikling" ~ 2,
    Status == "Mangler data" ~ 3
  )) %>%
  arrange(sortby, sortby2 ) %>%
  filter(Type != "Egne forslag") %>%
  select(c("GBF Mål", "Indikatorer", "Status")) %>%
  kbl(align="ll",
      booktabs = TRUE) %>%
  kable_classic("striped",
                 full_width = F) %>%
  row_spec(0, bold=T) %>%
    pack_rows("Headline indikatorer", 1, a, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Component indikatorer", a+1, b, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Complementary indikatorer", b+1,c, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Miljøindikatorer", c+1,d, label_row_css = "background-color: #cef598; color: #000000;") %>%
    pack_rows("Nasjonale målepunkt", d+1,e, label_row_css = "background-color: #cef598; color: #000000;" ) #%>%
 
#The table is too long for an image. Copy the text in the output and paset directly (wit formatting) into word 
#save_kable("indikatorer.jpg", 
 #            zoom = 2)
```
